# -*- coding: utf-8 -*-
"""Morana, Valentina - Parte 2 – Algoritmo de navegación en Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TiHY8Uhg8ADYKFrEMuCI1HmsbpB8u7Vj

**Parte 2 – Algoritmo de navegación en Python**

Segundo Parcial Robótica
"""

import requests
import json
ROBOT_ID = "valen"
ROBOT_KEY = "ardilla contemplativa"
urlApi = 'http://168.226.218.194:8006/Ester'


def enviar_post(comando,type,velocity,position,rotation,onoff,data):
    global ROBOT_ID,ROBOT_KEY
    data={
      "api_key": "acc$2g1",
      "user_id": "pepe",
      "user_key": "qwe123",
      "user_to": "simulador",
      "object_id":ROBOT_ID,
      "object_key":ROBOT_KEY,
      "command":str(comando),
      "type":str(type),
      "velocity":velocity,
      "position":position,
      "rotation":rotation,
      "on":onoff,
      "data":str(data)
    }
    response = requests.post(urlApi, json=data)

    print("Status code: ", response.status_code)
    return(response.json())

def leer_post(comando,type):
    global ROBOT_ID,ROBOT_KEY
    data={
      "api_key": "acc$2g1",
      "user_id": "pepe",
      "user_key": "qwe123",
      "user_to": "simulador",
      "object_id":ROBOT_ID,
      "object_key":ROBOT_KEY,
      "command":str(comando),
      "type":str(type)
    }
    response = requests.post(urlApi, json=data)

    print("Status code: ", response.status_code)
    return(response.json())

def enviar_put(robot_id,robot_key,comando,type,velocity,position,rotation,onoff,data):
    global ROBOT_ID,ROBOT_KEY
    data={
      "api_key": "acc$2g1",
      "user_id": "pepe",
      "user_key": "qwe123",
      "user_to": "simulador",
      "object_id":ROBOT_ID,
      "object_key":ROBOT_KEY,
      "command":str(comando),
      "type":str(type),
      "velocity":velocity,
      "position":position,
      "rotation":rotation,
      "on":onoff,
      "data":str(data)
    }
    response = requests.put(urlApi, json=data)

    print("Status code: ", response.status_code)
    return(response.json())

def send_seteo(type,onoff=False,data=""):
    global ROBOT_ID,ROBOT_KEY
    data={
      "api_key": "acc$2g1",
      "user_id": "pepe",
      "user_key": "qwe123",
      "user_to": "simulador",
      "object_id":ROBOT_ID,
      "object_key":ROBOT_KEY,
      "command":"seteo",
      "type":str(type),
      "on":onoff,
      "data":str(data)
    }
    response = requests.put(urlApi, json=data)

    print("Status code: ", response.status_code)
    return(response.json())

def send_mover(type,velocity):
    global ROBOT_ID,ROBOT_KEY
    data={
      "api_key": "acc$2g1",
      "user_id": "pepe",
      "user_key": "qwe123",
      "user_to": "simulador",
      "object_id":ROBOT_ID,
      "object_key":ROBOT_KEY,
      "command":"mover",
      "type":str(type),
      "velocity":velocity
    }
    response = requests.put(urlApi, json=data)

    print("Status code: ", response.status_code)
    return(response.json())


def leer_put(comando,type):
    global ROBOT_ID,ROBOT_KEY
    data={
      "api_key": "acc$2g1",
      "user_id": "pepe",
      "user_key": "qwe123",
      "user_to": "simulador",
      "object_id":ROBOT_ID,
      "object_key":ROBOT_KEY,
      "command":str(comando),
      "type":str(type)
    }
    response = requests.put(urlApi, json=data)

    print("Status code: ", response.status_code)
    return(response.json())


def send_rotate(x,y,z):
    global ROBOT_ID,ROBOT_KEY
    data={
      "api_key": "acc$2g1",
      "user_id": "pepe",
      "user_key": "qwe123",
      "user_to": "simulador",
      "object_id":ROBOT_ID,
      "object_key":ROBOT_KEY,
      "command":"mover",
      "type":"rotar",
      "rotation":{"x":x,"y":y,"z":z}
    }
    response = requests.put(urlApi, json=data)
    #enviar_put(robot_id,robot_key,"mover","rotar","","","",{"x":0,"y":45,"z":0},"","")
    print("Status code: ", response.status_code)
    return(response.json())

def send_teleport(x,y,z):
    global ROBOT_ID,ROBOT_KEY
    data={
      "api_key": "acc$2g1",
      "user_id": "pepe",
      "user_key": "qwe123",
      "user_to": "simulador",
      "object_id":ROBOT_ID,
      "object_key":ROBOT_KEY,
      "command":"mover",
      "type":"teletransportar",
      "position":{"x":x,"y":y,"z":z}
    }
    response = requests.put(urlApi, json=data)
    #enviar_put(robot_id,robot_key,"mover","rotar","","","",{"x":0,"y":45,"z":0},"","")
    print("Status code: ", response.status_code)
    return(response.json())

def robot_avanzar(velocity):
  send_mover("avanzar",velocity)

def robot_retroceder(velocity):
  send_mover("retroceder",velocity)

def robot_derecha(velocity):
  send_mover("derecha",velocity)

def robot_izquierda(velocity):
  send_mover("izquierda",velocity)

def robot_detener():
  send_mover("detener","","")

def robot_saltar(velocity):
  send_mover("saltar",velocity,"")

def teletransportar(x,y,z):
  send_teleport(x,y,z)

def rotar(x,y,z):
   send_rotate(x,y,z)

"""---
**Controles básicos**
"""

robot_retroceder(10)

teletransportar(0,2,0)

rotar(0,90,0)

robot_avanzar(150)

robot_derecha(15)

robot_izquierda(20)

"""---
**Funcionamiento de la carrera**
---


"""

teletransportar(115,5,15)
rotar(0,270,0)

for x in range(2):
  robot_avanzar(20)
  time.sleep(2)
rotar(0,180,0)
time.sleep(1)
for x in range(2):
  robot_avanzar(40)
  time.sleep(3)
rotar(0,90,0)
time.sleep(1)
for x in range(4):
  robot_avanzar(20)
  time.sleep(2)
rotar(0,0,0)
time.sleep(1)
for x in range(2):
  robot_avanzar(40)
  time.sleep(3)
rotar(0,270,0)
time.sleep(1)
for x in range(2):
  robot_avanzar(20)
  time.sleep(2)