# -*- coding: utf-8 -*-
"""TP1 "Python para robótica" - Morana, Valentina

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BpHOZJeHr2Q2Hur4h3mvaB3gYDvpfZNi

**TP1 "Python para robótica"**

Repositorio https://gitlab.com/nbalich/python_basico_robotica/-/tree/master
"""

# -*- coding: UTF-8 -*-
# Programa integrador de ejemplos (basado en repos de python_basico_robotica)
# Incluye: clases/funciones, fecha/hora (zona Argentina), suma con input, factorial, manejo de errores interactivo, entrada de datos.

import math
from datetime import datetime
import pytz   # librería para manejar zonas horarias

# -----------------------------
# (1) CLASES Y FUNCIONES (clases_y_funciones.py)
# -----------------------------
class Operaciones:
    def cuadrado(self, x):
        return x * x

    def seno(self, ang_en_radianes):
        return math.sin(ang_en_radianes)

def mostrar_fecha():
    """Imprime la fecha/hora actual en Argentina (Buenos Aires)."""
    tz = pytz.timezone("America/Argentina/Buenos_Aires")
    now = datetime.now(tz)
    print("Fecha y hora actual (Buenos Aires):", now.strftime("%Y-%m-%d %H:%M:%S"))

def setup():
    """Inicializa variables de control (internas)."""
    global g_controlador, g_now
    g_controlador = "INICIALIZADO"
    g_now = datetime.now(pytz.timezone("America/Argentina/Buenos_Aires"))

# -----------------------------
# (2) SUMA CON ENTRADA DEL USUARIO (basado en sumas_con_constantes.py)
# -----------------------------
def suma_con_constantes():
    """Pide al usuario dos números y muestra su suma."""
    try:
        a = float(input("Ingresá el valor de A: "))
        b = float(input("Ingresá el valor de B: "))
        print(f"A = {a}, B = {b}")
        print("A + B =", a + b)
    except ValueError:
        print("Error: Debés ingresar números.")

# -----------------------------
# (3) FACTORIAL (factorial.py)
# -----------------------------
def factorial(n):
    if n < 0:
        raise ValueError("El factorial no está definido para negativos.")
    if n == 0:
        return 1
    return n * factorial(n - 1)

# -----------------------------
# (4) TRAPEO DE ERRORES (trapeo_errores.py)
#     Ahora interactivo: el usuario ingresa el divisor
# -----------------------------
def demo_trapeo_errores():
    try:
        n = float(input("Ingresá un número para dividir 10 por él: "))
        resultado = 10 / n
        print("División correcta =", resultado)
    except ZeroDivisionError:
        print("Error: no se puede dividir por cero.")
    except ValueError:
        print("Error: ingresá un número válido.")

# -----------------------------
# (5) ENTRADA DE DATOS (nuevo agregado)
# -----------------------------
def pedir_nombre_y_edad():
    """Pide nombre y edad al usuario y los muestra."""
    try:
        nombre = input("Ingresá tu nombre: ")
        edad = int(input("Ingresá tu edad: "))
        print("Hola,", nombre, "tu edad es", edad, "años.")
    except ValueError:
        print("Error: la edad debe ser un número entero.")

# -----------------------------
# Utilidades de entrada segura
# -----------------------------
def pedir_float(msg):
    while True:
        try:
            return float(input(msg))
        except ValueError:
            print("Entrada inválida. Ingresá un número.")

def pedir_int(msg):
    while True:
        try:
            return int(input(msg))
        except ValueError:
            print("Entrada inválida. Ingresá un entero.")

# -----------------------------
# SUBMENÚS
# -----------------------------
def submenu_aritmetica():
    ops = Operaciones()
    while True:
        print("\n--- MÓDULO ARITMÉTICO ---")
        print("[1] Cuadrado (Operaciones.cuadrado)")
        print("[2] Seno (en radianes) (Operaciones.seno)")
        print("[3] Suma con números ingresados por el usuario")
        print("[4] Factorial (recursivo)")
        print("[5] Manejo de errores (división por cero)")
        print("[0] Volver")
        op = input("Elegí una opción: ").strip()

        if op == "1":
            x = pedir_float("Ingresá un número: ")
            print("cuadrado(", x, ") =", ops.cuadrado(x))
        elif op == "2":
            ang = pedir_float("Ingresá un ángulo en radianes: ")
            print("seno(", ang, ") =", ops.seno(ang))
        elif op == "3":
            suma_con_constantes()
        elif op == "4":
            n = pedir_int("Ingresá un entero (≥ 0): ")
            try:
                print(f"{n}! =", factorial(n))
            except ValueError as e:
                print("Error:", e)
        elif op == "5":
            demo_trapeo_errores()
        elif op == "0":
            return
        else:
            print("Opción inválida.")

def submenu_sistema():
    while True:
        print("\n--- MÓDULO SISTEMA ---")
        print("[1] Mostrar fecha/hora actual (Argentina)")
        print("[2] Ingresar nombre y edad")
        print("[0] Volver")
        op = input("Elegí una opción: ").strip()

        if op == "1":
            mostrar_fecha()
        elif op == "2":
            pedir_nombre_y_edad()
        elif op == "0":
            return
        else:
            print("Opción inválida.")

# -----------------------------
# PROGRAMA PRINCIPAL
# -----------------------------
def main():
    setup()  # inicializa variables internas
    while True:
        print("\n=== PROGRAMA INTEGRADO (6 EJEMPLOS) ===")
        print("[1] Módulo Aritmético")
        print("[2] Módulo Sistema")
        print("[0] Salir")
        op = input("Elegí una opción: ").strip()

        if op == "1":
            submenu_aritmetica()
        elif op == "2":
            submenu_sistema()
        elif op == "0":
            print("¡Chau!")
            break
        else:
            print("Opción inválida.")

if __name__ == "__main__":
    main()